run_name: "" # your run name
run_strategy: "epoch"
run_duration: 5
seed: 322
dry_run: False
save_folder: "" # your save folder
device_train_batch_size: 128
device_eval_batch_size: 128
max_grad_norm: 1.0
precision: bf16
gradient_accumulation_steps: 1
activation_checkpointing: True
accelerator_type: "gpu"
console_log_interval: 100

checkpoint:
  save_num_checkpoints_to_keep: 100
  save_interval: 1
  save_strategy: "epoch"

optimizer:
  name: "adamw"
  learning_rate: 0.00001
  weight_decay: 1.0
  betas: [ 0.9, 0.95 ]

scheduler:
  name: "cosine_annealing"
  t_warmup: 200
  t_factor: 0.01
  t_min: 0.

evaluators:
  type: 
    - "clip_cls"
  eval_interval: 1
  eval_strategy: "epoch"

wandb:
  enabled: False
  project: "" # your wandb project name
  group: "" # your wandb group name
  name: "" # your wandb run name
  log_interval: 100
  

deepspeed:
  enabled: True
  stage: 2

fsdp:
  enabled: False