### model
model_name_or_path: "" # your model path
trust_remote_code: true
flash_attn: fa2
resume_from_checkpoint: "" # your resume checkpoint path


### method
stage: "" # your stage name
do_train: true
finetuning_type: full
lora_target: all
freeze_trainable_modules: "merger"
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: false  # choices: [true, false]
train_mm_proj_only: true  # choices: [true, false]
deepspeed: "" # your deepspeed config path

### dataset
dataset: "" # your dataset name
dataset_dir: "" # your dataset directory
template: "" # your template name
cutoff_len: 8192
max_pixels: 768
max_samples: null
preprocessing_num_workers: 16
dataloader_num_workers: 8
tokenized_path: "" # your tokenized path

### output
output_dir: "" # your output directory
logging_steps: 1
save_steps: 1500
plot_loss: true
overwrite_output_dir: true
report_to: all
run_name: "" # your run name

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 8.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
weight_decay: 0.01
